name: Walkathon Reminder

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every 1 minute (change to '0 12 * * *' for 12 PM daily)
  workflow_dispatch:       # Allows manual triggering too

jobs:
  run-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run webhook script
        run: python WalkathonReminder.py
